version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql/data:z
    env_file:
      - db.env
    deploy:
      replicas: 1
      placement:
        constraints: [ node.hostname==attopi ]
  app:
    image: hoyolab_login_manager:latest
    configs:
      - app_config
    environment:
      - RUST_LOG=info
    deploy:
      replicas: 1
      placement:
        constraints: [ node.hostname==attopi ]

volumes:
  db:
configs:
  app_config:
    file: ./config.yml
